spring:
  application:
    name: search
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: http://localhost:9200
  kafka:
    consumer:
      bootstrap-servers: localhost:29091,localhost:29091,localhost:29091
      group-id: search
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
logging:
  level:
    org:
      springframework:
        web: info
        boot: info
server:
  port: 8890
